version: '3'

services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB_NAME
      POSTGRES_DB_NAME: $POSTGRES_DB_NAME
    ports:
      - "5432:5432"
    volumes:
      - ./database/.data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - ./database/servers.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
    ports:
      - "8080:80"
    depends_on:
      - database
  backend:
    image: node:18-alpine3.16
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./backend/:/app
    ports:
      - 1337:1337
    command: npm run develop
    depends_on:
      - database